import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";

// POST - Seed complet avec données réalistes de Médiouna
export async function POST() {
  try {
    // 1. Vérifier/créer les communes de Médiouna
    const communesData = [
      { nom: 'Médiouna', population: 45000 },
      { nom: 'Tit Mellil', population: 35000 },
      { nom: 'Lahraouiyine', population: 28000 },
      { nom: 'Bouskoura', population: 52000 },
      { nom: 'Nouaceur', population: 45000 },
    ];

    const communes: any[] = [];
    for (const c of communesData) {
      let commune = await prisma.commune.findFirst({ where: { nom: c.nom } });
      if (!commune) {
        commune = await prisma.commune.create({
          data: { 
            nom: c.nom, 
            code: c.nom.replace(/\s+/g, '-').toUpperCase(),
            population: c.population,
            region: 'Casablanca-Settat',
            province: 'Médiouna',
          },
        });
      } else {
        commune = await prisma.commune.update({
          where: { id: commune.id },
          data: { population: c.population },
        });
      }
      communes.push(commune);
    }

    // 2. Créer 20 établissements réalistes
    const etablissementsData = [
      // ÉDUCATION (5)
      {
        code: 'EDU-MED-001',
        nom: 'Lycée Qualifiant Ibn Khaldoun',
        nomArabe: 'ثانوية ابن خلدون التأهيلية',
        secteur: 'EDUCATION',
        nature: 'Lycée Qualifiant',
        tutelle: 'Ministère de l\'Éducation Nationale',
        gestionnaire: 'Direction Provinciale de l\'Éducation',
        responsableNom: 'M. Ahmed Bennani',
        telephone: '0522-75-84-21',
        email: 'lycee.ibnkhaldoun@education.ma',
        adresseComplete: 'Avenue Hassan II, Centre Médiouna',
        quartierDouar: 'Centre Ville',
        latitude: 33.4502,
        longitude: -7.5198,
        capaciteAccueil: 1200,
        effectifTotal: 980,
        etatInfrastructure: 'BON',
        services: ['Bibliothèque', 'Laboratoire Sciences', 'Salle Informatique', 'Terrain de Sport'],
        programmes: ['Baccalauréat Sciences', 'Baccalauréat Lettres', 'Baccalauréat Économie'],
        anneeCreation: 1985,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.3,
        nombreEvaluations: 45,
      },
      {
        code: 'EDU-MED-002',
        nom: 'Collège Al Massira',
        nomArabe: 'إعدادية المسيرة',
        secteur: 'EDUCATION',
        nature: 'Collège',
        tutelle: 'Ministère de l\'Éducation Nationale',
        gestionnaire: 'Direction Provinciale de l\'Éducation',
        responsableNom: 'Mme Fatima Zahra El Alami',
        telephone: '0522-75-82-15',
        email: 'college.almassira@education.ma',
        adresseComplete: 'Rue Al Massira, Quartier Industriel',
        quartierDouar: 'Quartier Industriel',
        latitude: 33.4480,
        longitude: -7.5150,
        capaciteAccueil: 800,
        effectifTotal: 720,
        etatInfrastructure: 'BON',
        services: ['Bibliothèque', 'Salle Multimédia', 'Cantine Scolaire'],
        programmes: ['Enseignement Secondaire Collégial'],
        anneeCreation: 1992,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.1,
        nombreEvaluations: 38,
      },
      {
        code: 'EDU-MED-003',
        nom: 'École Primaire Al Amal',
        nomArabe: 'مدرسة الأمل الابتدائية',
        secteur: 'EDUCATION',
        nature: 'École Primaire',
        tutelle: 'Ministère de l\'Éducation Nationale',
        gestionnaire: 'Direction Provinciale de l\'Éducation',
        responsableNom: 'M. Karim Tazi',
        telephone: '0522-75-81-30',
        email: 'ecole.alamal@education.ma',
        adresseComplete: 'Douar Oulad Saleh, Route de Tit Mellil',
        quartierDouar: 'Oulad Saleh',
        latitude: 33.4550,
        longitude: -7.5100,
        capaciteAccueil: 450,
        effectifTotal: 420,
        etatInfrastructure: 'MOYEN',
        services: ['Cantine Scolaire', 'Transport Scolaire'],
        programmes: ['Enseignement Primaire'],
        anneeCreation: 1978,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 3.9,
        nombreEvaluations: 28,
      },
      {
        code: 'EDU-TIT-001',
        nom: 'Groupe Scolaire Tit Mellil',
        nomArabe: 'مجموعة مدارس تيط مليل',
        secteur: 'EDUCATION',
        nature: 'Groupe Scolaire',
        tutelle: 'Ministère de l\'Éducation Nationale',
        gestionnaire: 'Direction Provinciale de l\'Éducation',
        responsableNom: 'Mme Naima Berrada',
        telephone: '0522-74-63-15',
        email: 'gs.titmellil@education.ma',
        adresseComplete: 'Centre Tit Mellil, Avenue Mohammed V',
        quartierDouar: 'Centre',
        latitude: 33.5520,
        longitude: -7.4850,
        capaciteAccueil: 600,
        effectifTotal: 550,
        etatInfrastructure: 'BON',
        services: ['Bibliothèque', 'Aire de Jeux', 'Cantine'],
        programmes: ['Préscolaire', 'Primaire'],
        anneeCreation: 1995,
        statutFonctionnel: 'Actif',
        communeId: communes[1].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.2,
        nombreEvaluations: 35,
      },
      {
        code: 'EDU-BOU-001',
        nom: 'Lycée Bouskoura International',
        nomArabe: 'ثانوية بوسكورة الدولية',
        secteur: 'EDUCATION',
        nature: 'Lycée International',
        tutelle: 'Ministère de l\'Éducation Nationale',
        gestionnaire: 'AREF Casablanca-Settat',
        responsableNom: 'M. Youssef Alaoui',
        telephone: '0522-33-45-67',
        email: 'lycee.bouskoura@education.ma',
        adresseComplete: 'Zone Résidentielle Bouskoura',
        quartierDouar: 'Bouskoura Golf City',
        latitude: 33.4350,
        longitude: -7.6520,
        capaciteAccueil: 1500,
        effectifTotal: 1200,
        etatInfrastructure: 'EXCELLENT',
        services: ['Piscine', 'Gymnase', 'Laboratoires', 'Auditorium', 'WiFi'],
        programmes: ['Baccalauréat International', 'Baccalauréat Marocain'],
        anneeCreation: 2010,
        statutFonctionnel: 'Actif',
        communeId: communes[3].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.7,
        nombreEvaluations: 62,
      },
      // SANTÉ (4)
      {
        code: 'SAN-MED-001',
        nom: 'Centre de Santé Médiouna',
        nomArabe: 'المركز الصحي الميدونة',
        secteur: 'SANTE',
        nature: 'Centre de Santé Urbain',
        tutelle: 'Ministère de la Santé',
        gestionnaire: 'Délégation Provinciale de la Santé',
        responsableNom: 'Dr. Rachid El Mansouri',
        telephone: '0522-75-80-00',
        email: 'cs.mediouna@sante.gov.ma',
        adresseComplete: 'Avenue Mohammed V, Centre Médiouna',
        quartierDouar: 'Centre Ville',
        latitude: 33.4510,
        longitude: -7.5180,
        capaciteAccueil: 200,
        effectifTotal: 35,
        etatInfrastructure: 'BON',
        services: ['Consultation Générale', 'Vaccination', 'Soins Infirmiers', 'Planning Familial', 'Laboratoire'],
        programmes: ['Santé Maternelle', 'Vaccination Nationale', 'Lutte contre les Maladies Chroniques'],
        anneeCreation: 1990,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.0,
        nombreEvaluations: 52,
      },
      {
        code: 'SAN-MED-002',
        nom: 'Dispensaire Rural Oulad Saleh',
        nomArabe: 'مستوصف أولاد صالح القروي',
        secteur: 'SANTE',
        nature: 'Dispensaire Rural',
        tutelle: 'Ministère de la Santé',
        gestionnaire: 'Délégation Provinciale de la Santé',
        responsableNom: 'Dr. Amina Chakir',
        telephone: '0522-75-85-42',
        email: 'dispensaire.ouladsaleh@sante.gov.ma',
        adresseComplete: 'Douar Oulad Saleh, Route Provinciale 3011',
        quartierDouar: 'Oulad Saleh',
        latitude: 33.4620,
        longitude: -7.5050,
        capaciteAccueil: 50,
        effectifTotal: 12,
        etatInfrastructure: 'MOYEN',
        services: ['Consultation Générale', 'Soins de Base', 'Vaccination'],
        programmes: ['Santé Rurale', 'Caravanes Médicales'],
        anneeCreation: 2005,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 3.7,
        nombreEvaluations: 18,
      },
      {
        code: 'SAN-TIT-001',
        nom: 'Centre de Santé Tit Mellil',
        nomArabe: 'المركز الصحي تيط مليل',
        secteur: 'SANTE',
        nature: 'Centre de Santé Urbain',
        tutelle: 'Ministère de la Santé',
        gestionnaire: 'Délégation Provinciale de la Santé',
        responsableNom: 'Dr. Hassan Ouazzani',
        telephone: '0522-74-62-00',
        email: 'cs.titmellil@sante.gov.ma',
        adresseComplete: 'Boulevard Mohammed VI, Tit Mellil',
        quartierDouar: 'Centre',
        latitude: 33.5535,
        longitude: -7.4870,
        capaciteAccueil: 150,
        effectifTotal: 28,
        etatInfrastructure: 'BON',
        services: ['Consultation Générale', 'Pédiatrie', 'Maternité', 'Urgences'],
        programmes: ['Santé Mère-Enfant', 'Prévention Diabète'],
        anneeCreation: 1998,
        statutFonctionnel: 'Actif',
        communeId: communes[1].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.2,
        nombreEvaluations: 41,
      },
      {
        code: 'SAN-NOU-001',
        nom: 'Hôpital Local Nouaceur',
        nomArabe: 'المستشفى المحلي النواصر',
        secteur: 'SANTE',
        nature: 'Hôpital Local',
        tutelle: 'Ministère de la Santé',
        gestionnaire: 'Direction Régionale de la Santé',
        responsableNom: 'Dr. Mohammed Fassi Fihri',
        telephone: '0522-53-42-00',
        email: 'hopital.nouaceur@sante.gov.ma',
        adresseComplete: 'Route Aéroportuaire, Nouaceur',
        quartierDouar: 'Centre',
        latitude: 33.3680,
        longitude: -7.5820,
        capaciteAccueil: 120,
        effectifTotal: 85,
        etatInfrastructure: 'BON',
        services: ['Urgences 24h', 'Chirurgie', 'Maternité', 'Radiologie', 'Laboratoire'],
        programmes: ['Urgences', 'Chirurgie Ambulatoire'],
        anneeCreation: 2008,
        statutFonctionnel: 'Actif',
        communeId: communes[4].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.4,
        nombreEvaluations: 78,
      },
      // SPORT (4)
      {
        code: 'SPO-MED-001',
        nom: 'Complexe Sportif de Proximité Médiouna',
        nomArabe: 'المركب الرياضي للجوار الميدونة',
        secteur: 'SPORT',
        nature: 'Complexe Sportif',
        tutelle: 'Ministère de la Jeunesse et des Sports',
        gestionnaire: 'Commune de Médiouna',
        responsableNom: 'M. Omar Benjelloun',
        telephone: '0522-75-83-50',
        email: 'complexe.sport.mediouna@mjsl.gov.ma',
        adresseComplete: 'Quartier Al Massira, Médiouna',
        quartierDouar: 'Al Massira',
        latitude: 33.4485,
        longitude: -7.5120,
        capaciteAccueil: 500,
        effectifTotal: 15,
        etatInfrastructure: 'EXCELLENT',
        services: ['Terrain Football', 'Piste Athlétisme', 'Salle Musculation', 'Vestiaires'],
        programmes: ['École de Football', 'Athlétisme Jeunes', 'Fitness'],
        anneeCreation: 2018,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.5,
        nombreEvaluations: 67,
      },
      {
        code: 'SPO-MED-002',
        nom: 'Stade Municipal de Médiouna',
        nomArabe: 'الملعب البلدي الميدونة',
        secteur: 'SPORT',
        nature: 'Stade Municipal',
        tutelle: 'Commune de Médiouna',
        gestionnaire: 'Service des Sports',
        responsableNom: 'M. Abdellah Rahmouni',
        telephone: '0522-75-84-00',
        email: 'stade.mediouna@commune.ma',
        adresseComplete: 'Avenue des FAR, Médiouna',
        quartierDouar: 'Centre',
        latitude: 33.4520,
        longitude: -7.5220,
        capaciteAccueil: 3000,
        effectifTotal: 8,
        etatInfrastructure: 'BON',
        services: ['Terrain Football', 'Tribunes', 'Éclairage', 'Parkings'],
        programmes: ['Championnats Locaux', 'Tournois Inter-Quartiers'],
        anneeCreation: 1982,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 3.8,
        nombreEvaluations: 24,
      },
      {
        code: 'SPO-BOU-001',
        nom: 'Golf Royal de Bouskoura',
        nomArabe: 'نادي الغولف الملكي بوسكورة',
        secteur: 'SPORT',
        nature: 'Club de Golf',
        tutelle: 'Fédération Royale Marocaine de Golf',
        gestionnaire: 'Association Golf Bouskoura',
        responsableNom: 'M. Adil Mesfioui',
        telephone: '0522-33-48-00',
        email: 'contact@golfbouskoura.ma',
        siteWeb: 'https://www.golfbouskoura.ma',
        adresseComplete: 'Bouskoura Golf City',
        quartierDouar: 'Golf City',
        latitude: 33.4280,
        longitude: -7.6480,
        capaciteAccueil: 400,
        effectifTotal: 45,
        etatInfrastructure: 'EXCELLENT',
        services: ['Parcours 18 Trous', 'Practice', 'Club House', 'Restaurant', 'Pro Shop'],
        programmes: ['Cours de Golf', 'Tournois', 'Événements Corporate'],
        anneeCreation: 2005,
        statutFonctionnel: 'Actif',
        communeId: communes[3].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.8,
        nombreEvaluations: 89,
      },
      {
        code: 'SPO-TIT-001',
        nom: 'Salle Omnisports Tit Mellil',
        nomArabe: 'القاعة متعددة الرياضات تيط مليل',
        secteur: 'SPORT',
        nature: 'Salle Omnisports',
        tutelle: 'Ministère de la Jeunesse et des Sports',
        gestionnaire: 'Commune Tit Mellil',
        responsableNom: 'Mme Khadija Naciri',
        telephone: '0522-74-65-80',
        email: 'salle.sport.titmellil@mjsl.gov.ma',
        adresseComplete: 'Rue du Sport, Tit Mellil',
        quartierDouar: 'Centre',
        latitude: 33.5515,
        longitude: -7.4890,
        capaciteAccueil: 800,
        effectifTotal: 10,
        etatInfrastructure: 'BON',
        services: ['Basketball', 'Volleyball', 'Handball', 'Arts Martiaux'],
        programmes: ['Ligue Scolaire', 'Compétitions Régionales'],
        anneeCreation: 2012,
        statutFonctionnel: 'Actif',
        communeId: communes[1].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.3,
        nombreEvaluations: 31,
      },
      // SOCIAL (4)
      {
        code: 'SOC-MED-001',
        nom: 'Dar Chabab Médiouna',
        nomArabe: 'دار الشباب الميدونة',
        secteur: 'SOCIAL',
        nature: 'Maison des Jeunes',
        tutelle: 'Ministère de la Jeunesse et des Sports',
        gestionnaire: 'Délégation Provinciale',
        responsableNom: 'M. Samir El Hadri',
        telephone: '0522-75-82-70',
        email: 'darchabab.mediouna@mjsl.gov.ma',
        adresseComplete: 'Avenue Al Qods, Médiouna',
        quartierDouar: 'Centre',
        latitude: 33.4505,
        longitude: -7.5165,
        capaciteAccueil: 200,
        effectifTotal: 8,
        etatInfrastructure: 'BON',
        services: ['Ateliers Artistiques', 'Salle Informatique', 'Bibliothèque', 'Salle Polyvalente'],
        programmes: ['Théâtre', 'Musique', 'Informatique', 'Langues'],
        anneeCreation: 1988,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.1,
        nombreEvaluations: 42,
      },
      {
        code: 'SOC-MED-002',
        nom: 'Centre d\'Écoute et d\'Orientation Familiale',
        nomArabe: 'مركز الإنصات والتوجيه الأسري',
        secteur: 'SOCIAL',
        nature: 'Centre Social',
        tutelle: 'Ministère de la Solidarité',
        gestionnaire: 'Entraide Nationale',
        responsableNom: 'Mme Soumaya Benkirane',
        telephone: '0522-75-86-20',
        email: 'ceofmediouna@entraide.ma',
        adresseComplete: 'Rue Ibn Sina, Médiouna',
        quartierDouar: 'Centre',
        latitude: 33.4495,
        longitude: -7.5175,
        capaciteAccueil: 50,
        effectifTotal: 12,
        etatInfrastructure: 'BON',
        services: ['Écoute', 'Médiation Familiale', 'Aide Juridique', 'Accompagnement Social'],
        programmes: ['Protection de l\'Enfance', 'Soutien aux Femmes'],
        anneeCreation: 2015,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.6,
        nombreEvaluations: 28,
      },
      {
        code: 'SOC-MED-003',
        nom: 'Coopérative Agricole Oulad Saleh',
        nomArabe: 'تعاونية أولاد صالح الفلاحية',
        secteur: 'SOCIAL',
        nature: 'Coopérative',
        tutelle: 'Office de Développement de la Coopération',
        gestionnaire: 'Conseil d\'Administration',
        responsableNom: 'M. Brahim Belkadi',
        telephone: '0522-75-89-10',
        email: 'coop.ouladsaleh@gmail.com',
        adresseComplete: 'Douar Oulad Saleh, Médiouna',
        quartierDouar: 'Oulad Saleh',
        latitude: 33.4580,
        longitude: -7.5030,
        capaciteAccueil: 100,
        effectifTotal: 45,
        etatInfrastructure: 'BON',
        services: ['Collecte Lait', 'Stockage Céréales', 'Vente Intrants'],
        programmes: ['Agriculture Durable', 'Formation Agriculteurs'],
        anneeCreation: 2008,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.0,
        nombreEvaluations: 15,
      },
      {
        code: 'SOC-LAH-001',
        nom: 'Centre de Formation Professionnelle Lahraouiyine',
        nomArabe: 'مركز التكوين المهني الهراويين',
        secteur: 'SOCIAL',
        nature: 'Centre de Formation',
        tutelle: 'OFPPT',
        gestionnaire: 'Direction Régionale OFPPT',
        responsableNom: 'M. Driss Tounsi',
        telephone: '0522-72-45-00',
        email: 'cfp.lahraouiyine@ofppt.ma',
        adresseComplete: 'Zone Industrielle Lahraouiyine',
        quartierDouar: 'Zone Industrielle',
        latitude: 33.5050,
        longitude: -7.5280,
        capaciteAccueil: 400,
        effectifTotal: 35,
        etatInfrastructure: 'EXCELLENT',
        services: ['Ateliers Pratiques', 'Salles de Cours', 'Cantine', 'Internat'],
        programmes: ['Électricité', 'Mécanique', 'Informatique', 'Commerce'],
        anneeCreation: 2010,
        statutFonctionnel: 'Actif',
        communeId: communes[2].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.4,
        nombreEvaluations: 56,
      },
      // CULTUREL (3)
      {
        code: 'CUL-MED-001',
        nom: 'Maison de la Culture Médiouna',
        nomArabe: 'دار الثقافة الميدونة',
        secteur: 'CULTUREL',
        nature: 'Maison de la Culture',
        tutelle: 'Ministère de la Culture',
        gestionnaire: 'Direction provinciale de la Culture',
        responsableNom: 'Mme Laila Bennani',
        telephone: '0522-75-81-00',
        email: 'maisonculture.mediouna@culture.gov.ma',
        adresseComplete: 'Place de l\'Indépendance, Médiouna',
        quartierDouar: 'Centre',
        latitude: 33.4508,
        longitude: -7.5190,
        capaciteAccueil: 350,
        effectifTotal: 12,
        etatInfrastructure: 'BON',
        services: ['Théâtre', 'Galerie d\'Art', 'Salle de Conférences', 'Bibliothèque'],
        programmes: ['Expositions', 'Concerts', 'Théâtre Amateur', 'Ateliers Artistiques'],
        anneeCreation: 1995,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.2,
        nombreEvaluations: 38,
      },
      {
        code: 'CUL-MED-002',
        nom: 'Bibliothèque Municipale Médiouna',
        nomArabe: 'المكتبة البلدية الميدونة',
        secteur: 'CULTUREL',
        nature: 'Bibliothèque',
        tutelle: 'Commune de Médiouna',
        gestionnaire: 'Service Culture',
        responsableNom: 'M. Mostafa Kadiri',
        telephone: '0522-75-80-50',
        email: 'bibliotheque.mediouna@commune.ma',
        adresseComplete: 'Rue Allal Ben Abdellah, Médiouna',
        quartierDouar: 'Centre',
        latitude: 33.4500,
        longitude: -7.5185,
        capaciteAccueil: 100,
        effectifTotal: 6,
        etatInfrastructure: 'BON',
        services: ['Lecture sur Place', 'Prêt de Livres', 'Espace Enfants', 'Internet'],
        programmes: ['Clubs de Lecture', 'Concours', 'Animation Jeunesse'],
        anneeCreation: 2000,
        statutFonctionnel: 'Actif',
        communeId: communes[0].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.0,
        nombreEvaluations: 22,
      },
      {
        code: 'CUL-BOU-001',
        nom: 'Espace d\'Art Contemporain Bouskoura',
        nomArabe: 'فضاء الفن المعاصر بوسكورة',
        secteur: 'CULTUREL',
        nature: 'Galerie d\'Art',
        tutelle: 'Fondation Bouskoura pour la Culture',
        gestionnaire: 'Association Art Contemporain',
        responsableNom: 'Mme Zineb Rhioui',
        telephone: '0522-33-50-00',
        email: 'art.bouskoura@fondation.ma',
        siteWeb: 'https://www.artbouskoura.ma',
        adresseComplete: 'Boulevard Principal, Bouskoura',
        quartierDouar: 'Centre',
        latitude: 33.4400,
        longitude: -7.6450,
        capaciteAccueil: 200,
        effectifTotal: 8,
        etatInfrastructure: 'EXCELLENT',
        services: ['Expositions', 'Ateliers', 'Résidences d\'Artistes', 'Boutique'],
        programmes: ['Expositions Temporaires', 'Art Contemporain', 'Rencontres Artistes'],
        anneeCreation: 2015,
        statutFonctionnel: 'Actif',
        communeId: communes[3].id,
        isPublie: true,
        isValide: true,
        noteMoyenne: 4.6,
        nombreEvaluations: 45,
      },
    ];

    const createdEtabs = [];
    for (const data of etablissementsData) {
      const existing = await prisma.etablissement.findUnique({ where: { code: data.code } });
      
      if (existing) {
        const updated = await prisma.etablissement.update({
          where: { code: data.code },
          data: {
            ...data,
            secteur: data.secteur as any,
            etatInfrastructure: data.etatInfrastructure as any,
            donneesSpecifiques: {},
          },
        });
        createdEtabs.push({ action: 'updated', nom: data.nom });
      } else {
        await prisma.etablissement.create({
          data: {
            ...data,
            secteur: data.secteur as any,
            etatInfrastructure: data.etatInfrastructure as any,
            donneesSpecifiques: {},
          },
        });
        createdEtabs.push({ action: 'created', nom: data.nom });
      }
    }

    // 3. Créer des événements réalistes
    const evenementsData = [
      {
        titre: 'Journée Portes Ouvertes - Lycée Ibn Khaldoun',
        description: 'Venez découvrir notre établissement, rencontrer les enseignants et visiter les installations. Au programme : présentation des filières, visite guidée, démonstrations des laboratoires et exposition des travaux d\'élèves.',
        secteur: 'EDUCATION',
        typeCategorique: 'Journée Portes Ouvertes',
        dateDebut: new Date('2025-01-15T09:00:00'),
        dateFin: new Date('2025-01-15T17:00:00'),
        heureDebut: '09:00',
        heureFin: '17:00',
        lieu: 'Lycée Ibn Khaldoun',
        capaciteMax: 500,
        organisateur: 'Direction du Lycée Ibn Khaldoun',
        emailContact: 'lycee.ibnkhaldoun@education.ma',
        contactOrganisateur: '0522-75-84-21',
      },
      {
        titre: 'Campagne de Vaccination Grippe Saisonnière',
        description: 'Campagne gratuite de vaccination contre la grippe saisonnière pour les personnes âgées, les malades chroniques et le personnel de santé. Apportez votre carte d\'identité et votre carnet de santé.',
        secteur: 'SANTE',
        typeCategorique: 'Campagne Santé',
        dateDebut: new Date('2025-01-10T08:00:00'),
        dateFin: new Date('2025-01-20T16:00:00'),
        heureDebut: '08:00',
        heureFin: '16:00',
        lieu: 'Centre de Santé Médiouna',
        capaciteMax: 1000,
        organisateur: 'Délégation Provinciale de la Santé',
        emailContact: 'cs.mediouna@sante.gov.ma',
        contactOrganisateur: '0522-75-80-00',
      },
      {
        titre: 'Tournoi Inter-Quartiers de Football',
        description: 'Grand tournoi de football réunissant les équipes des différents quartiers de Médiouna. Venez encourager votre équipe ! Prix et trophées pour les gagnants. Buvette et animation sur place.',
        secteur: 'SPORT',
        typeCategorique: 'Compétition Sportive',
        dateDebut: new Date('2025-02-01T14:00:00'),
        dateFin: new Date('2025-02-02T18:00:00'),
        heureDebut: '14:00',
        heureFin: '18:00',
        lieu: 'Stade Municipal de Médiouna',
        capaciteMax: 2000,
        organisateur: 'Service des Sports - Commune Médiouna',
        emailContact: 'stade.mediouna@commune.ma',
        contactOrganisateur: '0522-75-84-00',
      },
      {
        titre: 'Festival Culturel de Médiouna',
        description: 'Le Festival annuel de Médiouna vous invite à célébrer la culture locale avec des concerts de musique traditionnelle, des spectacles de danse, une exposition d\'artisanat et une soirée de poésie.',
        secteur: 'CULTUREL',
        typeCategorique: 'Festival',
        dateDebut: new Date('2025-03-20T18:00:00'),
        dateFin: new Date('2025-03-22T23:00:00'),
        heureDebut: '18:00',
        heureFin: '23:00',
        lieu: 'Maison de la Culture Médiouna',
        capaciteMax: 1500,
        organisateur: 'Direction Provinciale de la Culture',
        emailContact: 'maisonculture.mediouna@culture.gov.ma',
        contactOrganisateur: '0522-75-81-00',
      },
      {
        titre: 'Atelier d\'Insertion Professionnelle pour les Jeunes',
        description: 'Atelier de formation sur la rédaction de CV, la préparation aux entretiens et la recherche d\'emploi. Animé par des professionnels RH. Inscription obligatoire.',
        secteur: 'SOCIAL',
        typeCategorique: 'Formation',
        dateDebut: new Date('2025-01-25T09:00:00'),
        dateFin: new Date('2025-01-25T17:00:00'),
        heureDebut: '09:00',
        heureFin: '17:00',
        lieu: 'Dar Chabab Médiouna',
        capaciteMax: 50,
        organisateur: 'Dar Chabab - ANAPEC',
        emailContact: 'darchabab.mediouna@mjsl.gov.ma',
        contactOrganisateur: '0522-75-82-70',
      },
      {
        titre: 'Course à Pied "Médiouna Run" 10km',
        description: 'Première édition de la course Médiouna Run ! Parcours de 10km à travers la ville. Catégories : Hommes, Femmes, Vétérans. Médailles et lots pour tous les participants.',
        secteur: 'SPORT',
        typeCategorique: 'Compétition Sportive',
        dateDebut: new Date('2025-04-15T07:00:00'),
        dateFin: new Date('2025-04-15T12:00:00'),
        heureDebut: '07:00',
        heureFin: '12:00',
        lieu: 'Départ: Complexe Sportif Médiouna',
        capaciteMax: 500,
        organisateur: 'Association Sportive Médiouna',
        emailContact: 'complexe.sport.mediouna@mjsl.gov.ma',
        contactOrganisateur: '0522-75-83-50',
      },
      {
        titre: 'Caravane Médicale Gratuite',
        description: 'Caravane médicale pluridisciplinaire : consultations générales, ophtalmologie, dentaire, analyses médicales gratuites. Pour les habitants des zones rurales de Médiouna.',
        secteur: 'SANTE',
        typeCategorique: 'Campagne Santé',
        dateDebut: new Date('2025-02-08T08:00:00'),
        dateFin: new Date('2025-02-08T17:00:00'),
        heureDebut: '08:00',
        heureFin: '17:00',
        lieu: 'Dispensaire Oulad Saleh',
        capaciteMax: 300,
        organisateur: 'Délégation Provinciale de la Santé',
        emailContact: 'dispensaire.ouladsaleh@sante.gov.ma',
        contactOrganisateur: '0522-75-85-42',
      },
      {
        titre: 'Exposition "Artisanat de Médiouna"',
        description: 'Découvrez le savoir-faire artisanal de notre province : poterie, tissage, travail du cuir. Démonstrations par les artisans, vente directe et ateliers d\'initiation pour enfants.',
        secteur: 'CULTUREL',
        typeCategorique: 'Exposition',
        dateDebut: new Date('2025-02-15T10:00:00'),
        dateFin: new Date('2025-02-20T19:00:00'),
        heureDebut: '10:00',
        heureFin: '19:00',
        lieu: 'Bibliothèque Municipale Médiouna',
        capaciteMax: 200,
        organisateur: 'Chambre d\'Artisanat Médiouna',
        emailContact: 'bibliotheque.mediouna@commune.ma',
        contactOrganisateur: '0522-75-80-50',
      },
    ];

    // Récupérer les établissements pour les lier aux événements
    const etabsForEvents = await prisma.etablissement.findMany({
      where: { communeId: communes[0].id },
      take: 8,
    });

    // Récupérer un user pour createdBy (créer si n'existe pas)
    let adminUser = await prisma.user.findFirst({ where: { role: 'DELEGATION' } });
    if (!adminUser) {
      adminUser = await prisma.user.create({
        data: {
          email: 'delegation@mediouna.ma',
          nom: 'Délégation',
          prenom: 'Médiouna',
          motDePasse: '$2b$10$dummyhashedpassword',
          role: 'DELEGATION',
          isActive: true,
          secteurResponsable: 'EDUCATION',
        }
      });
    }

    const createdEvents = [];
    for (let i = 0; i < evenementsData.length; i++) {
      const data = evenementsData[i];
      const etab = etabsForEvents[i % etabsForEvents.length];
      
      if (!etab) continue;
      
      const event = await prisma.evenement.create({
        data: {
          titre: data.titre,
          description: data.description,
          typeCategorique: data.typeCategorique,
          secteur: data.secteur as any,
          statut: 'PUBLIEE' as any,
          dateDebut: data.dateDebut,
          dateFin: data.dateFin,
          heureDebut: data.heureDebut,
          heureFin: data.heureFin,
          lieu: data.lieu,
          capaciteMax: data.capaciteMax,
          organisateur: data.organisateur,
          emailContact: data.emailContact,
          contactOrganisateur: data.contactOrganisateur,
          nombreVues: Math.floor(Math.random() * 500) + 50,
          nombreInscrits: Math.floor(Math.random() * 100),
          etablissement: { connect: { id: etab.id } },
          commune: { connect: { id: communes[0].id } },
          createdByUser: { connect: { id: adminUser.id } },
        },
      });
      createdEvents.push({ titre: event.titre });
    }

    return NextResponse.json({
      success: true,
      message: "Données de test créées avec succès",
      communes: communes.length,
      etablissements: createdEtabs,
      evenements: createdEvents.length,
    });

  } catch (error) {
    console.error("Erreur seed complet:", error);
    return NextResponse.json({ error: "Erreur serveur", details: String(error) }, { status: 500 });
  }
}
